spring:
  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=gadgetdb;encrypt=false
    username: sa
    password: Myp@ssw0rd#2025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000
  app:
    jwt:
      secret: "change-me-to-a-very-long-random-string-at-least-32-chars"
      expiration-ms: 3600000
server:
  port: 8080
