spring:
  datasource:
      url: jdbc:sqlserver://mssql:1433;databaseName=gadgetdb;encrypt=false
      username: sa
      password: Myp@ssw0rd!1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  redis:
    host: localhost
    port: 6379
    timeout: 2000

server:
  port: 8080
